### ISSUE TITLE
Safe exception handling for backend errors

### ISSUE THREAD

**Issue by ianaf100** [SE-691-Graphing-Calculator/esoteric_nonsense#6]
We need a way to handle errors like divide by zero and pass an error message to the front end

**Comment by TPXS-Drexel** [comment]
divide by zero returns a nan.
i talked to greg and i think we should be sending results back as floats rather than strings

**Comment by ianaf100** [comment]
Okay, so all errors would just be NaN? But I'm also thinking about some form of exception handling, because right now everything crashes if there's an error. If anything, just for our sake while testing
